# -*- coding: utf-8 -*-
"""pred.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fBndSd9oQi35vKK7rsyyLnypmwSMWaF4
"""

model = load_model('modelvgg.h5')
img = image.load_img('/content/gdrive/My Drive/chest_xray/val/NORMAL/NORMAL2-IM-1431-0001.jpeg', target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
img_data = preprocess_input(x)
pred = model.predict(img_data)